# Generated by Django 4.2.3 on 2024-02-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=255, unique=True)),
                ('tq_pr', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('drawing', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('elev', models.CharField(blank=True, max_length=255, null=True)),
                ('prod', models.CharField(blank=True, max_length=255, null=True)),
                ('colour', models.CharField(blank=True, max_length=255, null=True)),
                ('ppc_side', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qty', models.PositiveIntegerField(blank=True, null=True)),
                ('total_lm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qty_1', models.PositiveIntegerField(blank=True, null=True)),
                ('total_lm_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_m2_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('welds', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phase', models.CharField(blank=True, max_length=255, null=True)),
                ('priority_1', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
