# Generated by Django 4.2.3 on 2024-02-20 21:00

from django.db import migrations, models
import django.db.models.deletion


def populate_database(apps, schema_editor):
    Client = apps.get_model('projects', 'Client')
    Client.objects.create(id='A0001', name='Klient testowy')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProjectElements',
            new_name='ProjectElement',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.client')),
            ],
        ),
        migrations.RunPython(populate_database),
    ]
