# Generated by Django 4.2.3 on 2024-02-22 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_client_rename_projectelements_projectelement_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectelement',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projects.project'),
            preserve_default=False,
        ),
    ]
