# Generated by Django 4.2.3 on 2024-02-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectelement_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectelement',
            name='welds',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
