# Generated by Django 4.2.3 on 2024-02-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectelement_welds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectelement',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectelement',
            name='qty_1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
