# Generated by Django 4.2.3 on 2024-03-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectelement_qty_alter_projectelement_qty_1'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectelement',
            unique_together={('project', 'ref')},
        ),
    ]
