# Generated by Django 4.2.3 on 2024-03-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectelement_ref'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectelement',
            unique_together={('project', 'ref', 'tq_pr')},
        ),
    ]
